# NAME-SANTANU BERA

USE MAVENMOVIES

# 6.Pull all the films with ‘Comedy’ category.
SELECT * FROM FILM
SELECT * FROM CATEGORY
SELECT * FROM FILM_CATEGORY
SELECT TITLE,NAME FROM FILM F INNER JOIN FILM_CATEGORY FM ON F.FILM_ID=FM.FILM_ID INNER JOIN
CATEGORY C ON FM.CATEGORY_ID=C.CATEGORY_ID WHERE NAME ='COMEDY' ORDER BY TITLE

# 5.Pull all the films which were rented and return in the month of May.
SELECT * FROM FILM
SELECT * FROM INVENTORY
SELECT * FROM RENTAL
SELECT TITLE,RENTAL_DATE,RETURN_DATE FROM FILM F INNER JOIN INVENTORY I ON F.FILM_ID=I.FILM_ID 
INNER JOIN RENTAL R ON I.INVENTORY_ID=R.INVENTORY_ID 
WHERE MONTHNAME(RENTAL_DATE)='MAY' AND MONTHNAME(RETURN_DATE)='MAY'

# 4.Pull all the films acted by the actor ‘Will Wilson’.
SELECT * FROM FILM
SELECT * FROM FILM_ACTOR
SELECT * FROM ACTOR
SELECT F.TITLE,CONCAT(A.FIRST_NAME,' ',A.LAST_NAME) AS ACTOR FROM FILM F JOIN FILM_ACTOR FA 
ON F.FILM_ID=FA.FILM_ID JOIN ACTOR A ON FA.ACTOR_ID=A.ACTOR_ID
WHERE FIRST_NAME='WILL' AND LAST_NAME='WILSON'

# 3.Find the actors who have acted in the film ‘Frost Head’.
SELECT * FROM FILM
SELECT * FROM FILM_ACTOR
SELECT * FROM ACTOR
SELECT A.FIRST_NAME,A.LAST_NAME,F.TITLE FROM ACTOR A JOIN FILM_ACTOR FA ON A.ACTOR_ID=FA.ACTOR_ID 
JOIN FILM F ON FA.FILM_ID=F.FILM_ID WHERE TITLE='FROST HEAD'

# 2.List all Oscar awardees(Actors who received Oscar award) with their full names 
    and length of their names.
SELECT * FROM ACTOR_AWARD
SELECT * FROM ACTOR_AWARD
SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) AS ACTOR_NAME,LENGTH(CONCAT(FIRST_NAME,LAST_NAME)) AS LENGTH,
AWARDS FROM ACTOR_AWARD WHERE AWARDS like '%OSCAR%' ORDER BY ACTOR_NAME 
 
# 1.Write a SQL query to count the number of characters except the spaces for each actor. 
	Return first 10 actors name length along with their name.    
SELECT * FROM ACTOR
SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) AS NAME,LENGTH(CONCAT(FIRST_NAME,LAST_NAME)) AS LENGTH 
FROM ACTOR LIMIT 10











